services:
  db-mysql:
    platform: linux/amd64
    image: mysql:5.7.40
    restart: always
    environment:
      - MYSQL_DATABASE=trello
      - MYSQL_ROOT_PASSWORD=123456
      - ./dbdata:/var/lib/mysql
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    ports:
      - "3306:3306"